version: '2'
services:
  web:
    image: registry.spin.nersc.gov/stefanl/stefanl-nginx-proxy:v1
    volumes:
    - /global/project/projectdirs/isguser/spin/stefanl-flask-demo-gateways/web/images:/srv:ro
    ports:
    - 8080:8080/tcp
    cap_drop:
    - ALL
    user: 46311:71216
    group_add:
    - nginx
    labels:
      io.rancher.container.pull_image: always
  app:
    image: registry.spin.nersc.gov/stefanl/stefanl-flask-fruitfly:v1
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo-initdb-password
    stdin_open: true
    tty: true
    secrets:
    - source: db.stefanl-flask-demo-gateways.mongo-initdb-password
      target: mongo-initdb-password
      mode: '0444'
      uid: '0'
      gid: '0'
    - source: app.stefanl-flask-demo-gateways.ssh_private_key
      target: ssh_private_key
      mode: '0400'
      uid: '46311'
      gid: '71216'

    labels:
      io.rancher.container.pull_image: always
  db:
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo-initdb-password
    volumes:
    - db.stefanl-flask-demo-gateways:/data/db
    cap_drop:
    - ALL
    cap_add:
    - CHOWN
    - SETGID
    - SETUID
    - DAC_OVERRIDE
    secrets:
    - source: db.stefanl-flask-demo-gateways.mongo-initdb-password
      target: mongo-initdb-password
      mode: '0444'
      uid: '0'
      gid: '0'
    labels:
      io.rancher.container.pull_image: always

secrets:
  db.stefanl-flask-demo-gateways.mongo-initdb-password:
    external: 'true'

secrets:
  app.stefanl-flask-demo-gateways.ssh_private_key:
    external: 'true'

volumes:
  db.stefanl-flask-demo-gateways:
    external: true
    driver: rancher-nfs
