version: '2'
services:
  web:
    image: nginx:stable
    volumes:
    - /global/project/projectdirs/isguser/spin/stefanl-flask-demo/web/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    - /global/project/projectdirs/isguser/spin/stefanl-flask-demo/web/images:/srv:ro
    ports:
    - 8080:8080/tcp
    cap_drop:
    - ALL
    user: 46311:71216
    group_add:
    - nginx
    labels:
      io.rancher.container.pull_image: always
  app:
    image: registry.spin.nersc.gov/das/spin-flask-demo-app:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo-initdb-password
    stdin_open: true
    tty: true
    secrets:
    - mode: '0444'
      uid: '0'
      gid: '0'
      source: db.stefanl-flask-demo.mongo-initdb-password
      target: mongo-initdb-password
    labels:
      io.rancher.container.pull_image: always
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo-initdb-password
    volumes:
    - db.stefanl-flask-demo:/data/db
    cap_drop:
    - ALL
    cap_add:
    - CHOWN
    - SETGID
    - SETUID
    secrets:
    - mode: '0444'
      uid: '0'
      gid: '0'
      source: db.stefanl-flask-demo.mongo-initdb-password
      target: mongo-initdb-password
    labels:
      io.rancher.container.pull_image: always

secrets:
  db.stefanl-flask-demo.mongo-initdb-password:
    external: 'true'

volumes:
  db.stefanl-flask-demo:
    external: true
    driver: rancher-nfs
